#!/usr/bin/env node
// Regenerate src/vt/keys.ts from the GhosttyKey enum in libghostty-vt's public
// header, at whatever commit ghostty-vt.pin.json points to.
//
//   node scripts/gen-keys.mjs
//
// The enum is positional (only the first entry is assigned a value), so the
// values are only meaningful for a specific commit. Regenerate whenever the
// pin moves; the round-trip test in src/vt/keys.test.ts guards the shape.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pin = JSON.parse(readFileSync(join(root, "ghostty-vt.pin.json"), "utf8"));
const header = `https://raw.githubusercontent.com/ghostty-org/ghostty/${pin.commit}/include/ghostty/vt/key/event.h`;

const res = await fetch(header);
if (!res.ok) throw new Error(`GET ${header} -> ${res.status}`);
const src = await res.text();

// Isolate the GhosttyKey enum body. The file also declares GhosttyKeyAction,
// whose members share the GHOSTTY_KEY_ prefix, so match the brace pair that
// closes GhosttyKey specifically rather than the first enum in the file.
const body = /\{([^{}]*)\}\s*GhosttyKey;/.exec(src)?.[1];
if (!body) throw new Error("could not locate the GhosttyKey enum in event.h");

let next = 0;
const entries = [];
for (const line of body.split("\n")) {
  const m = /^\s*GHOSTTY_KEY_([A-Z0-9_]+)\s*(?:=\s*([^,]+?))?\s*,/.exec(line);
  if (!m) continue;
  const [, name, explicit] = m;
  if (name === "MAX_VALUE") continue;
  if (explicit !== undefined) {
    const n = Number(explicit.trim());
    if (!Number.isInteger(n)) throw new Error(`non-numeric enum value: ${line.trim()}`);
    next = n;
  }
  entries.push([name, next]);
  next += 1;
}
if (entries.length < 100) throw new Error(`only parsed ${entries.length} keys; header shape changed?`);

// A GhosttyKey name is the W3C KeyboardEvent.code with underscores where the
// camel-case humps are, so stripping underscores and lowercasing both sides
// makes the lookup exact rather than a hand-maintained table. The one
// exception is the letter keys: code "KeyA" against GHOSTTY_KEY_A.
const normalized = new Map();
for (const [name, value] of entries) {
  const key = name.replaceAll("_", "").toLowerCase();
  if (normalized.has(key)) throw new Error(`normalized key collision: ${key}`);
  normalized.set(key, value);
}

const lines = [
  "// Generated by scripts/gen-keys.mjs — do not edit.",
  `// Source: ghostty-org/ghostty@${pin.commit.slice(0, 12)} include/ghostty/vt/key/event.h`,
  `// Build:  ${pin.version}`,
  "",
  "/** GhosttyKey enum values, keyed by the C name without its GHOSTTY_KEY_ prefix. */",
  "export const GHOSTTY_KEY: Readonly<Record<string, number>> = Object.freeze({",
  ...entries.map(([name, value]) => `  ${name}: ${value},`),
  "});",
  "",
  "/**",
  " * GhosttyKey values keyed by KeyboardEvent.code lowercased with no separators.",
  " * Use keyForCode() rather than indexing this directly.",
  " */",
  "const BY_NORMALIZED_CODE: Readonly<Record<string, number>> = Object.freeze({",
  ...[...normalized].map(([key, value]) => `  ${JSON.stringify(key)}: ${value},`),
  "});",
  "",
  "/** GHOSTTY_KEY_UNIDENTIFIED — the value for a code libghostty does not know. */",
  "export const KEY_UNIDENTIFIED = 0;",
  "",
  "/**",
  " * Map a DOM KeyboardEvent.code to a GhosttyKey value.",
  " *",
  " * Returns KEY_UNIDENTIFIED for codes libghostty has no name for, which is a",
  " * valid thing to encode: the key event still carries its UTF-8 text.",
  " */",
  "export function keyForCode(code: string): number {",
  "  const letter = /^Key([A-Z])$/.exec(code);",
  "  const normalized = (letter ? letter[1] : code).toLowerCase();",
  "  return BY_NORMALIZED_CODE[normalized] ?? KEY_UNIDENTIFIED;",
  "}",
  "",
];

mkdirSync(join(root, "src", "vt"), { recursive: true });
writeFileSync(join(root, "src", "vt", "keys.ts"), lines.join("\n"));
process.stdout.write(`  wrote src/vt/keys.ts (${entries.length} keys from ${pin.commit.slice(0, 12)})\n`);
